package com.adasoft.adapos5mobile.model.`return`

import com.google.gson.annotations.SerializedName


data class CmlAoTPSTSalDT (

	@SerializedName("rtBchCode") val rtBchCode : String,
	@SerializedName("rtXshDocNo") val rtXshDocNo : String,
	@SerializedName("rnXsdSeqNo") val rnXsdSeqNo : Int,
	@SerializedName("rtPdtCode") val rtPdtCode : String,
	@SerializedName("rtXsdPdtName") val rtXsdPdtName : String,
	@SerializedName("rtPunCode") val rtPunCode : String,
	@SerializedName("rtPunName") val rtPunName : String,
	@SerializedName("rtPplCode") val rtPplCode : String,
	@SerializedName("rcXsdFactor") val rcXsdFactor : Int,
	@SerializedName("rtXsdBarCode") val rtXsdBarCode : String,
	@SerializedName("rtSrnCode") val rtSrnCode : String,
	@SerializedName("rtXsdVatType") val rtXsdVatType : String,
	@SerializedName("rtVatCode") val rtVatCode : String,
	@SerializedName("rcXsdVatRate") val rcXsdVatRate : Int,
	@SerializedName("rtXsdSaleType") val rtXsdSaleType : String,
	@SerializedName("rcXsdSalePrice") val rcXsdSalePrice : Int,
	@SerializedName("rcXsdQty") val rcXsdQty : Int,
	@SerializedName("rcXsdQtyAll") val rcXsdQtyAll : Int,
	@SerializedName("rcXsdSetPrice") val rcXsdSetPrice : Int,
	@SerializedName("rcXsdAmtB4DisChg") val rcXsdAmtB4DisChg : Int,
	@SerializedName("rtXsdDisChgTxt") val rtXsdDisChgTxt : String,
	@SerializedName("rcXsdDis") val rcXsdDis : Int,
	@SerializedName("rcXsdChg") val rcXsdChg : Int,
	@SerializedName("rcXsdNet") val rcXsdNet : Int,
	@SerializedName("rcXsdNetAfHD") val rcXsdNetAfHD : Int,
	@SerializedName("rcXsdVat") val rcXsdVat : Int,
	@SerializedName("rcXsdVatable") val rcXsdVatable : Int,
	@SerializedName("rcXsdWhtAmt") val rcXsdWhtAmt : Int,
	@SerializedName("rtXsdWhtCode") val rtXsdWhtCode : String,
	@SerializedName("rcXsdWhtRate") val rcXsdWhtRate : Int,
	@SerializedName("rcXsdCostIn") val rcXsdCostIn : Int,
	@SerializedName("rcXsdCostEx") val rcXsdCostEx : Int,
	@SerializedName("rtXsdStaPdt") val rtXsdStaPdt : String,
	@SerializedName("rcXsdQtyLef") val rcXsdQtyLef : Int,
	@SerializedName("rcXsdQtyRfn") val rcXsdQtyRfn : Int,
	@SerializedName("rtXsdStaPrcStk") val rtXsdStaPrcStk : String,
	@SerializedName("rtXsdStaAlwDis") val rtXsdStaAlwDis : String,
	@SerializedName("rnXsdPdtLevel") val rnXsdPdtLevel : Int,
	@SerializedName("rtXsdPdtParent") val rtXsdPdtParent : String,
	@SerializedName("rcXsdQtySet") val rcXsdQtySet : Int,
	@SerializedName("rtPdtStaSet") val rtPdtStaSet : String,
	@SerializedName("rtXsdRmk") val rtXsdRmk : String,
	@SerializedName("rdLastUpdOn") val rdLastUpdOn : String,
	@SerializedName("rtLastUpdBy") val rtLastUpdBy : String,
	@SerializedName("rdCreateOn") val rdCreateOn : String,
	@SerializedName("rtCreateBy") val rtCreateBy : String
)